### ISSUE TITLE
Tool Compilation

### ISSUE THREAD

**Issue by spcljense** [throwaway96/downgr8#3]
Dear sir Throwaway96,

I have a question about the downgr8 tool.
Yesterday i've spend all day trying to get a toolchain working to compile this app.
It has been a very long time for me compiling applications like openwrt firmware and stuff.
Unfortunately i cant get it to work properly.

Normally i would never ask or bother you, But is there a small possibility to get a compiled ipk?

Thank you very much in advance.

Best regards,
SpclJense

**Comment by throwaway96** [comment]
I would rather not provide IPKs for this. TBH, I'm not even sure it's in working condition.

You can build the binary with [buildroot-nc4](https://github.com/openlgtv/buildroot-nc4). To avoid the error in #2, you can either compile openlgtv/buildroot-nc4@1d1e847 or later yourself or just comment out the `static_assert` line.

To create the IPK, you'll need `ares-package` from the [webOS CLI tools](https://github.com/webos-tools/cli) (which are brand new; previously, the preferred option would have been the [webOS TV CLI tools](https://webostv.developer.lge.com/develop/tools/cli-installation)).

**Comment by spcljense** [comment]
I totally understand your opinion about this, I would like to use it at my own risk.
For me its important to get away from the engineering firmware back to stock.
I cant connect to my tv anymore with calman or any other calibration software to display patterns from the build in pattern generator. Incoming connections to ip and port of the tv are broken. Did a factory reset and im not happy with the white balance of my LG CX so calibration is a must for me. If i cant get my original firmware back then i guess its time for me to buy a LG G4.

**Comment by throwaway96** [comment]
I'm not sure how they connect to the TV, but presumably via SSAP. Whatever Luna requests they make also be done via SSH/telnet using `luna-send`.

Check that `allowMobileDeviceAccess` is enabled (the value can be seen in `/var/luna/preferences/network`).

**Comment by spcljense** [comment]
allowMobileDeviceAccess could be set to false indeed.
Thanks for the tip!

**Comment by spcljense** [comment]
allowMobileDeviceAccess seems fine.

**Comment by throwaway96** [comment]
You can probably get more help on the [OpenLGTV Discord](https://discord.gg/xWqRVEm).

**Comment by sareik** [comment]
> I would rather not provide IPKs for this. TBH, I'm not even sure it's in working condition.
> 
> You can build the binary with [buildroot-nc4](https://github.com/openlgtv/buildroot-nc4). To avoid the error in #2, you can either compile [openlgtv/buildroot-nc4@1d1e847](https://github.com/openlgtv/buildroot-nc4/commit/1d1e847) or later yourself or just comment out the `static_assert` line.
> 
> To create the IPK, you'll need `ares-package` from the [webOS CLI tools](https://github.com/webos-tools/cli) (which are brand new; previously, the preferred option would have been the [webOS TV CLI tools](https://webostv.developer.lge.com/develop/tools/cli-installation)).

I can confirm that the tool does not start properly, it stops after the message "downgr8 starting" 

![webos-dev-tmp-045ddecd-7f75-430e-964c-81fdbd588b1d-kopia](https://github.com/throwaway96/downgr8/assets/106591135/90e9dd11-ea0d-48ab-80de-4f9d5ffaa399)

After running the "patch" binary, it stops at "found diff 0x084908; final offset 0x658908"

I don't know if these logs will help to find the problem, if you need other logs I will be happy to send them to you
[legacy-log messages.zip](https://github.com/throwaway96/downgr8/files/14549909/legacy-log.messages.zip)

Device Info:
OLED55B23LA, FW Version: 13.40.41, webOS version: 8.3.0, OTAID: HE_DTV_W22H_AFABATPU

**Comment by throwaway96** [comment]
If you didn't see any errors, that means it worked. You have to enable expert mode and launch the update UI yourself afterward.

*Be aware that if the TV becomes unbootable and was not already in DEBUG mode, the only option for recovery is rewriting the eMMC with a programmer.* That would involve either soldering wires to the board on the necessary signals (if you can find them; accessing them may involve scraping away soldermask) or desoldering and resoldering the eMMC.

I recommend backing up the eMMC before downgrading, so that even if the eMMC is somehow totally destroyed you can theoretically reconstruct everything on a new chip. The main things to back up are the DRM keys, as those can't be replaced. I have a script that tries to back up all important partitions automatically, but I have to clean it up before I release it. [`backup-part.sh`](https://gist.github.com/throwaway96/1558bc833029224005b794009a2aa8b1#file-backup-part-sh) will dump an individual partition by ID.

After running the app:

0. Make sure you have the desired firmware image in `LG_DTV` on a USB drive. The image can be either NSU or USB, but I recommend USB.
1. This should say that `expertMode` is false:
    ```
    luna-send -q 'expertMode' -n 1 'luna://com.webos.service.update/getExpertMode' '{}'
    ```
2. So enable it (which would normally not be allowed without authenticated AccessUSB):
    ```
    luna-send -n 1 'luna://com.webos.service.update/setExpertMode' '{"mode":true}'
    ````
3. Check that `expertMode` is now enabled:
    ```
    luna-send -q 'expertMode' -n 1 'luna://com.webos.service.update/getExpertMode' '{}'
    ```
4. Launch update UI in Expert mode:
    ```
    luna-send -n 1 'luna://com.webos.service.applicationmanager/launch' '{"id":"com.webos.app.softwareupdate","params":{"mode":"expert","flagUpdate":true}}'
    ```
5. Select image and start the update process. I honestly don't know whether "Ext.MICOM" should be enabled or not.
6. You should probably perform a factory reset after downgrading (although only if you have a way to regain root, I guess).

I just pushed some local changes I had that may make the app slightly more reliable when run the first time.

Downgrading from webOS 23 to webOS 22 may be more dangerous than usual. Definitely do a factory reset after that.

**Comment by svlock** [comment]
> If you didn't see any errors, that means it worked. You have to enable expert mode and launch the update UI yourself afterward.


Hi,

Can I confirm "downgr8 Starting..." toast is all I need to see before running commands via SSH? I receive: 

`root@LGwebOSTV:~# luna-send -n 1 'luna://com.webos.service.update/setExpertMode'
 '{"mode":true}'
{ "returnValue": false, "errorCode": -3, "errorText": "Error has occurred in the process" }` 

In webOS Dev Manager debug section I can see the following in the log and it basically repeats forever, running over and over in this cycle:

> [03:27:03.385][WARNING] <default-lib> LS_MSG Encountered ECONNRESET during recv: fd: 8 {"ERROR_CODE":104,"ERROR":"Connection reset by peer","EXE":"(null)","APP_ID":"lol.downgr8.service","UNIQUE_NAME":"OB2w3EHD"}
> 
> [03:27:03.386][WARNING] <default-lib> LS_QUEUE _LSTransportHandleShutdownWithSerial: requeueing 1 messages for service "lol.downgr8.service" {"APP_ID":"lol.downgr8.service"}
> 
> [03:27:03.387][WARNING] ls-hubd LSHUB_SRV_CONN_DUP Duplicate request service name com.webos.lunasendpub-13509 from lol.downgr8.service. {"source_name":"x3N468WN","dest_name":"OB2w3EHD"}
> 
> [03:27:03.387][WARNING] ls-hubd LSHUB_NO_SERVICE _LSHubSendQueryNameReplyMessage: Failed Connecting to Service err_code: -1, service_name: "lol.downgr8.service", unique_name: "OB2w3EHD", dynamic, fd -1 {}
> 
> [03:27:03.387][ERR] ls-hubd LSHUB_SENDMSG LUNASERVICE ERROR {"ERROR_CODE":0,"ERROR":"(null)","FUNC":"(null)","FILE":"(null)","LINE":0}
> 
> [03:27:03.387][WARNING] ls-hubd LS_MSG Encountered ECONNRESET during recv: fd: 132 {"ERROR_CODE":104,"ERROR":"Connection reset by peer","EXE":"/usr/bin/node","APP_ID":"lol.downgr8.service","UNIQUE_NAME":"OB2w3EHD"}
> 
> [03:27:03.388][WARNING] <default-lib> LS_MSG _LSTransportHandleQueryNameFailure: retrying sending query name to service "lol.downgr8.service", 7 retries remain {"APP_ID":"lol.downgr8.service"}
> 
> [03:27:03.390][INFO] ls-hubd LSHUB_SRV_LNCH  {"SERVICE_NAME":"lol.downgr8.service","EXE":"/usr/sbin/setcpushares-ls2 /usr/bin/run-js-service -n /media/developer/apps/usr/palm/services/lol.downgr8.service","REQUESTER":"com.webos.lunasendpub-13509","APP_ID":"(null)","STATE":3,"PID":13619}
> 
> [03:27:03.399][INFO] ls-hubd LSHUB_SRV_EXIT  {"SERVICE_NAME":"lol.downgr8.service","EXE":"/usr/sbin/setcpushares-ls2 /usr/bin/run-js-service -n /media/developer/apps/usr/palm/services/lol.downgr8.service","STATE":3,"EXIT_CODE":0,"RESPAWN":1,"PID":13619}
> 
> [03:27:03.561][INFO] jailer JAILER_INFO file lock appid: lol.downgr8.service {}
> 
> [03:27:03.609][INFO] jailer JAILER_INFO file unlock appid: lol.downgr8.service {}
> 
> [03:27:03.609][WARNING] jailer JAILER_INFO app launch exec(/usr/bin/node,  /usr/bin/node --harmony /usr/palm/services/jsservicelauncher/bootstrap-node.js -- /tmp/run-js-service-no-cgroup /var/palm/ls2-dev /media/developer/apps/usr/palm/services/lol.downgr8.service) {}`

and it repeats

> [03:27:06.160][WARNING] <default-lib> LS_MSG Encountered ECONNRESET during recv: fd: 8 {"ERROR_CODE":104,"ERROR":"Connection reset by peer","EXE":"(null)","APP_ID":"lol.downgr8.service","UNIQUE_NAME":"hqVlF5Qc"}
> 
> [03:27:06.160][WARNING] <default-lib> LS_QUEUE _LSTransportHandleShutdownWithSerial: requeueing 1 messages for service "lol.downgr8.service" {"APP_ID":"lol.downgr8.service"}
> 
> [03:27:06.161][WARNING] ls-hubd LS_MSG Encountered ECONNRESET during recv: fd: 132 {"ERROR_CODE":104,"ERROR":"Connection reset by peer","EXE":"/usr/bin/node","APP_ID":"lol.downgr8.service","UNIQUE_NAME":"hqVlF5Qc"}
> 
> [03:27:06.163][INFO] ls-hubd LSHUB_SRV_LNCH  {"SERVICE_NAME":"lol.downgr8.service","EXE":"/usr/sbin/setcpushares-ls2 /usr/bin/run-js-service -n /media/developer/apps/usr/palm/services/lol.downgr8.service","REQUESTER":"com.webos.lunasendpub-13509","APP_ID":"(null)","STATE":3,"PID":13670}
> 
> [03:27:06.182][INFO] ls-hubd LSHUB_SRV_EXIT  {"SERVICE_NAME":"lol.downgr8.service","EXE":"/usr/sbin/setcpushares-ls2 /usr/bin/run-js-service -n /media/developer/apps/usr/palm/services/lol.downgr8.service","STATE":3,"EXIT_CODE":0,"RESPAWN":1,"PID":13670}
> 
> [03:27:06.347][INFO] jailer JAILER_INFO file lock appid: lol.downgr8.service {}
> 
> [03:27:06.402][INFO] jailer JAILER_INFO file unlock appid: lol.downgr8.service {}
> 
> [03:27:06.402][WARNING] jailer JAILER_INFO app launch exec(/usr/bin/node,  /usr/bin/node --harmony /usr/palm/services/jsservicelauncher/bootstrap-node.js -- /tmp/run-js-service-no-cgroup /var/palm/ls2-dev /media/developer/apps/usr/palm/services/lol.downgr8.service) {}`

Any advice is appreciated!

**Comment by throwaway96** [comment]
Looks like the service is crashing.

**Comment by svlock** [comment]
> Looks like the service is crashing.

Could it be an error I made compiling? 

While it always reports expertMode is false, before running the app launching software update results in nothing. After running the app, launching software update results in the TV going to black screen for varying amounts of time (for as little as 1 second to as long as 40 seconds on one occasion) and then jumping to home screen. 

So it's doing something, but not quite getting all the way there.

**Comment by fingers986** [comment]
Hi! Do you find any solutions?

**Comment by spcljense** [comment]
> Hi! Do you find any solutions?

Check the forks, Someone else made some changes. Also written a more in depth description on how to use it.

https://github.com/riversedge/downgr8
